preview/preview/urls.py
from django.contrib import admin
from django.urls import path
from preview_app import views as preview_app_view
from conference import views as conference_view
from presentation import views as presentation_view
from presentation.views import button_open_pptx
from planning import views as planning_views


urlpatterns = [

    # -----------------------------------------------------------------------------------| Accueil |----------------------------------------------------------------------------------- #
    path('', conference_view.accueil, name='accueil'),

    # -----------------------------------------------------------------------------------| Admin |----------------------------------------------------------------------------------- #
    path('admin/', admin.site.urls),


    # -----------------------------------------------------------------------------------| Conference |----------------------------------------------------------------------------------- #
    path('conference/', conference_view.index, name='conference'),


    # -----------------------------------------------------------------------------------| Presentation |----------------------------------------------------------------------------------- #
    path('presentation/', presentation_view.presentation, name='presentation'),

    path('ouvrir-presentation/', button_open_pptx, name='button_open_pptx'),

    path('add_presentation/', presentation_view.add_presentation, name="add_presentation"),
    
    # -----------------------------------------------------------------------------------| Planning |----------------------------------------------------------------------------------- #
    path('planning/', planning_views.planning, name='planning'),
    #path('planning/<int:jour_id>/', planning_views.jour, name='jour'),
    path('planning_ajout/', planning_views.ajout_salle, name='ajout_salle'),
    path('planning_update/', planning_views.update_text, name='update_text'),

    # -----------------------------------------------------------------------------------| Gestion |----------------------------------------------------------------------------------- #
    path('gestion/', planning_views.jour, name='gestion'),
    path('gestion/jour=<int:jour_id>/', planning_views.jour_detail, name='jour_detail'),
    
]

preview/presentation/models.py
from django.db import models

# Create your models here.

preview/preview_app/models.py
from django.db import models
from django.core.validators import FileExtensionValidator

# Create your models here.

class Conference(models.Model):

    def __str__(self):
        return f'{self.titre}'

    titre = models.fields.CharField(max_length=50)
    description = models.fields.CharField(max_length=255)
    logo = models.ImageField(upload_to='preview_app/static/images', blank=True, null=True)

class Jour(models.Model):

    def __str__(self):
        return f'{self.date}'

    date = models.DateField()



class Salle(models.Model):

    def __str__(self):
        return f'{self.titre}'

    titre = models.fields.CharField(max_length=50)
    # Date a corriger pour afficher que les jours
    # date = models.fields.DateField()
    


class Session(models.Model):

    def __str__(self):
        return f'{self.titre}'

    titre = models.fields.CharField(max_length=50)
    # Date a corriger pour les horraires
    duree = models.IntegerField()
    id_salle = models.ForeignKey(Salle, on_delete=models.CASCADE)

class Intervenant(models.Model):

    def __str__(self):
        return f'{self.nom, self.prenom}'

    nom = models.fields.CharField(max_length=50)
    prenom = models.fields.CharField(max_length=50)

    # Photo à voir si token ou autre manière à enregistrer
    logo = models.ImageField(upload_to='', blank=True, null=True)

class Presentation(models.Model):

    def __str__(self):
        return f'{self.titre}'

    titre = models.fields.CharField(max_length=50)
    description = models.fields.CharField(max_length=255)

    # Pptx a voir comment ça va être enregistré
    fichier_pptx = models.FileField(upload_to='preview_app/static/pptx/', validators=[FileExtensionValidator(['pptx'])])
    id_session = models.ForeignKey(Session, on_delete=models.CASCADE)

# A demander comment faire la table croisée

class InterPresent(models.Model):

    def __str__(self):
        return f'{self.id_presentation}'

    id_presentation = models.ForeignKey(Presentation, on_delete=models.CASCADE)
    id_intervenant = models.ForeignKey(Intervenant,null= True, on_delete=models.SET_NULL)

preview/presentation/forms.py
from django import forms
from preview_app.models import Presentation

class PresentationForm(forms.ModelForm):
    class Meta:
        model = Presentation
        fields = ['titre', 'description', 'fichier_pptx', 'id_session']

preview/presentation/views.py
from django.shortcuts import render, redirect
from preview_app.models import Presentation, InterPresent
from presentation.forms import PresentationForm
import socket
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from flask import Flask, request

app = Flask(__name__)

# Create your views here.

def presentation(request):
    presentations = Presentation.objects.all().prefetch_related('interpresent_set__id_intervenant')
    # print('hello')
    return render(request ,'presentation/presentation.html', {'presentations': presentations})


def add_presentation(request):
    if request.method == 'POST':
        form = PresentationForm(request.POST, request.FILES)
        if form.is_valid():
            presentation = form.save()
            # Do something with the saved presentation
    else:
        form = PresentationForm()
    return render(request, 'presentation/add_presentation.html', {'form': form})

def open_ppt(host, ppt_file):
    host = host
    port = 5000
    message = f"open_ppt@{ppt_file}".encode()
    # create socket
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        # connect to server
        sock.connect((host, port))
        # send string to server
        sock.sendall(message)
        # get server response
        response = sock.recv(1024)
        # decode the response and return it
        return response.decode()


def button_open_pptx(request):
    presentation_id = request.POST.get('presentation_id')
    print('Le formulaire a été soumis avec la valeur presentation_id :', presentation_id)

    presentation = Presentation.objects.get(id=presentation_id)
    fichier_pptx = presentation.fichier_pptx
    print(fichier_pptx.path)
    open_ppt("192.168.0.155", fichier_pptx.path)
    print('hello')
    return redirect('presentation')
    # return render(request, 'presentation/presentation.html', {})

preview/presentation/templates/presentation/add_presentation.html
{% extends "presentation/base.html" %}

{% block pres %}
    <div id="forms">
        <form action="{% url 'add_presentation' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Ajouter</button>
        </form>
    </div>
{% endblock %}

preview/presentation/templates/presentation/base.html
{% load static %}

<html>
    <head>
        <title>Presentation</title>
        <link rel="stylesheet" href="{% static 'css/presentation.css'%}">
    </head>
    <body>
        {% block pres %}{% endblock %}
    </body>
</html>

preview/presentation/templates/presentation/presentation.html
{% extends "presentation/base.html" %}
{% block pres %}

    <div id="forms">
        <a href="{% url 'add_presentation' %}">Ajouter presentation</a>
            <div class="head_box">
                {% csrf_token %}
            </div>
            <div id="big_box">
                <ul id="presta_box">
                    {% for presentation in presentations %}
                        <li id='presta_list'>
                            <div id='pp_box'><img src ='{{ presentation.id_intervenant.logo.url }}' id='pp'></div>
                            <div id='list'>
                                <h1>{{ presentation.titre }}</h1>
                                <p>{{ presentation.description }}</p>
                                <h4>
                                    {% for interpresent in presentation.interpresent_set.all %}
                                        {{ interpresent.id_intervenant.nom }} {{ interpresent.id_intervenant.prenom }}
                                    {% endfor %}
                                </h4>
                            </div>
                            <div data-modal-target='#modal' class='lien'>
                                <form action="{% url 'button_open_pptx' %}" id="form_{{ presentation.id }}" enctype="multipart/form-data" method="post" class="form-example">
                                    {% csrf_token %}
                                    <input type="hidden" name="presentation_id" value="{{ presentation.id }}">
                                    <input type="submit" class='btn-primary' value="Voilà tok">
                                </form>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
                
                
            </div>            
            <div class="footer_box">
                
            </div>
    </div>

{% endblock %}